apiVersion: v1
kind: Secret
metadata:
  name: rbi-compliance-secrets
  namespace: rbi-compliance
  labels:
    app: rbi-compliance
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  
  # JWT secrets
  JWT_SECRET: c3VwZXJfc2VjcmV0X2p3dF9rZXlfZm9yX3JiaV9jb21wbGlhbmNl  # super_secret_jwt_key_for_rbi_compliance
  JWT_REFRESH_SECRET: cmVmcmVzaF9zZWNyZXRfa2V5X2Zvcl9yYmlfY29tcGxpYW5jZQ==  # refresh_secret_key_for_rbi_compliance
  
  # Encryption keys
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfZm9yX3NlbnNpdGl2ZV9kYXRh  # encryption_key_for_sensitive_data
  
  # API keys for external services
  RBI_API_KEY: cmJpX2FwaV9rZXlfZm9yX3JlZ3VsYXRvcnlfaW50ZWdyYXRpb24=  # rbi_api_key_for_regulatory_integration
  CIBIL_API_KEY: Y2liaWxfYXBpX2tleV9mb3JfY3JlZGl0X2J1cmVhdQ==  # cibil_api_key_for_credit_bureau
  
  # Banking system credentials
  TEMENOS_API_KEY: dGVtZW5vc19hcGlfa2V5X2Zvcl9jb3JlX2Jhbmtpbmc=  # temenos_api_key_for_core_banking
  FINACLE_API_KEY: ZmluYWNsZV9hcGlfa2V5X2Zvcl9jb3JlX2Jhbmtpbmc=  # finacle_api_key_for_core_banking
  FLEXCUBE_API_KEY: ZmxleGN1YmVfYXBpX2tleV9mb3JfY29yZV9iYW5raW5n  # flexcube_api_key_for_core_banking
  
  # OAuth credentials
  OAUTH_CLIENT_SECRET: b2F1dGhfY2xpZW50X3NlY3JldF9mb3JfYXV0aGVudGljYXRpb24=  # oauth_client_secret_for_authentication
  
  # Email service credentials
  SMTP_PASSWORD: c210cF9wYXNzd29yZF9mb3JfZW1haWxfc2VydmljZQ==  # smtp_password_for_email_service
  
  # Webhook secrets
  WEBHOOK_SECRET: d2ViaG9va19zZWNyZXRfZm9yX3NlY3VyZV9kZWxpdmVyeQ==  # webhook_secret_for_secure_delivery
  
  # Monitoring credentials
  GRAFANA_ADMIN_PASSWORD: Z3JhZmFuYV9hZG1pbl9wYXNzd29yZA==  # grafana_admin_password

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rbi-compliance
  labels:
    app: postgres
    component: secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQxMjM=  # postgres_password123
  POSTGRES_REPLICATION_PASSWORD: cmVwbGljYXRpb25fcGFzc3dvcmQxMjM=  # replication_password123

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: rbi-compliance
  labels:
    app: redis
    component: secrets
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQxMjM=  # redis_password123

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: rbi-compliance
  labels:
    app: rabbitmq
    component: secrets
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cmJpX3VzZXI=  # rbi_user
  RABBITMQ_DEFAULT_PASS: cmFiYml0bXFfcGFzc3dvcmQxMjM=  # rabbitmq_password123

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: rbi-compliance
  labels:
    app: nginx
    component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key (base64 encoded)
  # These should be replaced with actual certificates in production
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t

---
# Secret for Docker registry access (if using private registry)
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: rbi-compliance
  labels:
    app: rbi-compliance
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiYXV0aCI6ImRYTmxjanB3WVhOemQyOXlaQT09In19fQ==

---
# Service account token secret for external API access
apiVersion: v1
kind: Secret
metadata:
  name: external-api-tokens
  namespace: rbi-compliance
  labels:
    app: rbi-compliance
    component: external-apis
type: Opaque
data:
  # External service tokens
  MONITORING_TOKEN: bW9uaXRvcmluZ190b2tlbl9mb3JfZXh0ZXJuYWxfYXBp  # monitoring_token_for_external_api
  BACKUP_SERVICE_TOKEN: YmFja3VwX3NlcnZpY2VfdG9rZW5fZm9yX2V4dGVybmFs  # backup_service_token_for_external
  
  # Third-party integration tokens
  SLACK_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvLi4u  # https://hooks.slack.com/services/...
  TEAMS_WEBHOOK_URL: aHR0cHM6Ly9vdXRsb29rLm9mZmljZS5jb20vd2ViaG9vay8uLi4=  # https://outlook.office.com/webhook/...

---
# Certificate authority secret for banking system connections
apiVersion: v1
kind: Secret
metadata:
  name: banking-ca-certs
  namespace: rbi-compliance
  labels:
    app: rbi-compliance
    component: banking-integration
type: Opaque
data:
  # CA certificates for banking systems (base64 encoded)
  temenos-ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  finacle-ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  flexcube-ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  
  # Client certificates for mutual TLS
  client.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  client.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
